#!/usr/bin/env bash
# scripts/codegen.sh — 拉 pm-cup2026 OpenAPI spec + 跑 oapi-codegen
#
# 输出：
#   pkg/clob/generated.go   (来自 services/clob-service/docs/openapi.yaml)
#   pkg/gamma/generated.go  (来自 services/gamma-service/api/openapi.yaml)
#
# 上游分支固定为 pm-v2（M10 release 锚点）。pm-cup2026 是 private repo，
# 拉取需 GitHub 凭据：本地优先 gh CLI（zerohacker666 登录），CI 走 GH_TOKEN env。

set -euo pipefail

REPO="chainupcloud/pm-cup2026"
REF="pm-v2"
CLOB_PATH="services/clob-service/docs/openapi.yaml"
GAMMA_PATH="services/gamma-service/api/openapi.yaml"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP="$ROOT/.tmp"

cleanup() { rm -rf "$TMP"; }
trap cleanup EXIT

mkdir -p "$TMP"

# 拉一个文件到指定路径；优先 gh api，失败回落 curl + GH_TOKEN
fetch() {
  local repo_path="$1" out="$2"
  if command -v gh >/dev/null 2>&1; then
    gh api "repos/$REPO/contents/$repo_path?ref=$REF" --jq '.content' \
      | base64 -d > "$out"
    return
  fi
  if [[ -n "${GH_TOKEN:-}${GITHUB_TOKEN:-}" ]]; then
    local tok="${GH_TOKEN:-$GITHUB_TOKEN}"
    curl -sSfL \
      -H "Authorization: Bearer $tok" \
      -H "Accept: application/vnd.github.raw" \
      "https://api.github.com/repos/$REPO/contents/$repo_path?ref=$REF" \
      -o "$out"
    return
  fi
  echo "codegen.sh: need gh CLI or GH_TOKEN/GITHUB_TOKEN to fetch private spec" >&2
  exit 1
}

if ! command -v oapi-codegen >/dev/null 2>&1; then
  echo "codegen.sh: installing oapi-codegen v2.6.0"
  GOBIN="$ROOT/.tmp/bin" go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.6.0
  export PATH="$ROOT/.tmp/bin:$PATH"
fi

echo "codegen.sh: fetching $REPO@$REF specs"
fetch "$CLOB_PATH"  "$TMP/clob-openapi.yaml"
fetch "$GAMMA_PATH" "$TMP/gamma-openapi.yaml"

echo "codegen.sh: generating pkg/clob/generated.go"
oapi-codegen --config "$ROOT/codegen-config-clob.yaml"  "$TMP/clob-openapi.yaml"

echo "codegen.sh: generating pkg/gamma/generated.go"
oapi-codegen --config "$ROOT/codegen-config-gamma.yaml" "$TMP/gamma-openapi.yaml"

# 在 generated 文件头部追加来源指针（oapi-codegen 自带 DO NOT EDIT，但补来源 URL 便于追溯）
prepend_source_header() {
  local file="$1" upstream="$2"
  local tmpf
  tmpf="$(mktemp)"
  {
    echo "// This file is generated by oapi-codegen. DO NOT EDIT."
    echo "//"
    echo "// Source: https://github.com/$REPO/blob/$REF/$upstream"
    echo "// Regenerate: ./scripts/codegen.sh"
    echo ""
    cat "$file"
  } > "$tmpf"
  mv "$tmpf" "$file"
}

prepend_source_header "$ROOT/pkg/clob/generated.go"  "$CLOB_PATH"
prepend_source_header "$ROOT/pkg/gamma/generated.go" "$GAMMA_PATH"

echo "codegen.sh: done"
